apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-test
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/djantzlur/fluxtest
  ref:
    branch: main

