apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: test-webhook
  namespace: flux-system
spec:
  type: generic
  address: http://alert.flux-system.svc.cluster.local:8080/
