apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: test-webhook
  namespace: flux-system
spec:
  type: generic
  address: https://webhook.site/19302ebe-383d-411c-8937-8bc9d71190ff
