# flux/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mychart
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxtest
    namespace: flux-system

