apiVersion: v1
kind: Pod
metadata:
  name: alert
  labels:
    app: alert
spec:
  containers:
  - name: flask
    image: python:3.10
    command: ["/bin/sh", "-c"]
    args:
      - pip install flask &&
        python /app/app.py
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: app-code
      mountPath: /app
  volumes:
  - name: app-code
    configMap:
      name: flask-app-code

